---
- name: "Get Cisco Device Info"
  hosts: all
  connection: network_cli
  gather_facts: no
  
  tasks:
  - name: Inventory Devices
    block:                
        - name: Gather facts (ios)
          ios_facts:
          register: result
          when: "'Cisco_IOS_Devices' in group_names"
          
        - name: Gather facts (nxos)
          nxos_facts:
          register: result
          when: "'Cisco_NXOS_Devices' in group_names"
          
        - name: Set vars discovery
          set_fact:
            discovery_complete: true
            cacheable: yes
          when: result is succeeded

    when: (ansible_facts['discovery_complete'] is undefined) or (not ansible_facts['discovery_complete']) or (force_refresh == "True")