---
- name: "Get Cisco Device Info"
  connection: network_cli
  hosts: all
  gather_facts: no
  
  tasks:
  - name: Inventory Devices
    block:                
        - name: Gather facts (ios)
          ios_facts:
          register: result
          ignore_errors: true
          
        - name: Gather facts (nxos)
          nxos_facts:
          register: result
          ignore_errors: true
          when: result is failed

    when: (ansible_facts['hostname'] is undefined) or (ansible_facts['hostname'] == "") or (ansible_facts['ansible_net_hostname'] is undefined) or (ansible_facts['ansible_net_hostname'] == "")