---
- name: "Get Cisco Device Info"
  hosts: all
  connection: network_cli
  gather_facts: no
  
  tasks:
    - name: Gather facts (ios)
      ios_facts:
      register: result
      ignore_errors: true
      
    - name: Gather facts (nxos)
      nxos_facts:
      register: result
      ignore_errors: true
      when: result is failed
      
    - name: Gather facts (iosxr)
      iosxr_facts:
      register: result
      ignore_errors: true
      when: result is failed
      
    - name: Gather facts (asa)
      iosxr_facts:
      register: result
      ignore_errors: true
      when: result is failed

      
      
    - name: Display some facts
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"