---
- name: "Get Cisco Device Info"
  hosts: all
  gather_facts: no
  
  tasks:
    - name: Gather facts (ios)
      ios_facts:

    - name: Gather facts (nxos)
      nxos_facts:

    - name: Gather facts (iosxr)
      iosxr_facts:

    - name: Gather facts (asa)
      iosxr_facts:

      
      
    - name: Display some facts
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"