---
- name: "Get Cisco Device Info"
  hosts: all
  connection: network_cli
  gather_facts: no
  
  tasks:
    - name: Gather facts (ios)
      ios_facts:
      when: ansible_network_os == 'ios'
    - name: Gather facts (nxos)
      nxos_facts:
      when: ansible_network_os == 'nxos'
    - name: Gather facts (iosxr)
      iosxr_facts:
      when: ansible_network_os == 'iosxr'
    - name: Gather facts (asa)
      iosxr_facts:
      when: ansible_network_os == 'asa'

      
      
    - name: Display some facts
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"