---
- name: "Install Linux Ldap Client"
  hosts: all
  become: true
  become_method: sudo

  tasks:
  - name: Install LinbNSS and Radius Auth
    apt:
      name: 
      - libnss-ldapd
      - libpam-radius-auth
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: /etc/nslcd.conf
    template:
      src: ./LDAP_Templates/nslcd.conf
      dest: /etc/nslcd.conf
      owner: root
      group: nslcd
      mode: 0640
      backup: yes

  - name: Add ldap to nsswitch.conf
    replace:
      path: /etc/nsswitch.conf
      regexp: "(^{{ item }}:(?!.*ldap).*$)"
      replace: '\1 ldap'
      backup: yes
    loop:
    - 'passwd'
    - 'group'
    - 'shadow'

  - name: Update unix auth to skip new entry
    pamd:
      name: common-auth
      type: auth
      control: '[success=2 default=ignore]'
      module_path: pam_unix.so
      new_control: '[success=3 default=ignore]'
      backup: yes
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: Insert a new rule pam_radius_auth.so 
    pamd:
      name: common-auth
      type: auth
      control: '[success=3 default=ignore]'
      module_path: pam_unix.so
      new_type: auth
      new_control: '[success=2 default=ignore]'
      new_module_path: pam_radius_auth.so
      state: after
      backup: yes
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: Make User Directories on login with pam_mkhomedir
    pamd:
      name: login
      type: session
      control: required
      module_path: pam_limits.so
      new_type: session
      new_control: required
      new_module_path: pam_mkhomedir.so
      state: after
      backup: yes
  - name: Add arguments to mkdir
    pamd:
      name: login
      type: session
      control: required
      module_path: pam_mkhomedir.so
      module_arguments: 'skel=/etc/skel/ umask=0077'
      state: updated