---
- name: "Set Cisco Banner"
  hosts: all
  gather_facts: no

  tasks:
    - name: Set IOS Devices
      block:                
      - name: CONFIGURE BANNER ON CISCO IOS DEVICES
        ios_banner:
          banner: login
          text: "{{ lookup('file', './docs/banner.cfg') }}"
          state: present

      when: ansible_network_os == "ios"

  tasks:
    - name: Set NXOS Devices
      block:                
      - name: CONFIGURE BANNER ON CISCO NXOS DEVICES
        nxos_banner:
          banner: login
          text: "{{ lookup('file', './docs/banner.cfg') }}"
          state: present

      when: ansible_network_os == "nxos"