---
- name: "Set Cisco SNMPv3"
  hosts: all
  gather_facts: no

#Must Provide snmpv3 custom credential and snmpv3_accessLevel variable via survey ("read" or "write")

  tasks:
  - name: Set IOS Devices
    block:                
      - name: Set Credential with auth/priv
        ios_config:
          lines:
            - snmp-server group {{ snmpv3_group }} v3 {{ snmpv3_level }} {{ snmpv3_accessLevel }} v1default
            - snmp-server user {{ snmpv3_username }} {{ snmpv3_group }} v3 auth {{ snmpv3_authType }} {{ snmpv3_authKey }} priv {{ snmpv3_privType }} {{ snmpv3_privKey }}
        when: snmpv3_level == "priv"

      - name: Set Credential with auth only
        ios_config:
          lines:
            - snmp-server group {{ snmpv3_group }} v3 {{ snmpv3_level }} {{ snmpv3_accessLevel }} v1default
            - snmp-server user {{ snmpv3_username }} {{ snmpv3_group }} v3 auth {{ snmpv3_authType }} {{ snmpv3_authKey }}
        when: snmpv3_level == "auth"

      - name: Set Credential with no auth/priv
        ios_config:
          lines:
            - snmp-server group {{ snmpv3_group }} v3 {{ snmpv3_level }} {{ snmpv3_accessLevel }} v1default
            - snmp-server user {{ snmpv3_username }} {{ snmpv3_group }} v3
        when: snmpv3_level == "noauth"

    when: ansible_network_os == "ios"

  - name: Set NXOS Devices
    block:                
      - name: Set Credential with auth/priv
        nxos_snmp_user:
          user: "{{ snmpv3_username }}"
          group: "{{ 'network-admin' if snmpv3_accessLevel == 'write' else 'network-operator' }}"
          authentication: "{{ snmpv3_authType }}"
          pwd: "{{ snmpv3_authKey }}"
          encrypt: yes
          privacy: "{{ snmpv3_privKey }}"
        when: snmpv3_level == "priv"

      - name: Set Credential with auth only
        nxos_snmp_user:
          user: "{{ snmpv3_username }}"
          group: "{{ 'network-admin' if snmpv3_accessLevel == 'write' else 'network-operator' }}"
          authentication: "{{ snmpv3_authType }}"
          pwd: "{{ snmpv3_authKey }}"
        when: snmpv3_level == "auth"

      - name: Set Credential with no auth/priv
        nxos_snmp_user:
          user: "{{ snmpv3_username }}"
          group: "{{ 'network-admin' if snmpv3_accessLevel == 'write' else 'network-operator' }}"
        when: snmpv3_level == "noauth"
        
    when: ansible_network_os == "nxos"