---
- name: "Set Cisco Enable Netconf"
  hosts: all
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Set IOS Devices
      block:
        - name: Enable Netconf on IOS Devices
          ios_config:
            lines:
              - netconf-yang
              - aaa authentication login default local
              - aaa authorization exec default local if-authenticated
            save_when: modified 

      when: ansible_network_os == "ios"
    
    - name: Set NXOS Devices
      block: 
        - name: Enable Netconf on NX-OS Devices
          nxos_feature:
            feature: netconf
            state: enabled

      when: ansible_network_os == "nxos"