---
- name: "SET HOSTNAME ON CISCO DEVICES"
  hosts: all
  gather_facts: no

  tasks:
    - name: Set IOS Devices
      block:
        - name: Set Hostname and Domain on IOS Devices
          ios_system:
            state: present # not required. choices: present;absent. State of the configuration values in the device's current active configuration.  When set to I(present), the values should be configured in the device active configuration and when set to I(absent) the values should not be in the device active configuration
            name_servers: # not required. List of DNS name servers by IP address to use to perform name resolution lookups.  This argument accepts either a list of DNS servers See examples.
              - "{{ NameServer1 }}"
              - "{{ NameServer2 }}"
            hostname: "{{ HostName }}" # not required. Configure the device hostname parameter. This option takes an ASCII string value.            
            domain_name: "{{ DomainName }}" # not required. Configure the IP domain name on the remote device to the provided value. Value should be in the dotted name form and will be appended to the C(hostname) to create a fully-qualified domain name.
            lookup_enabled: True # not required. Administrative control for enabling or disabling DNS lookups.  When this argument is set to True, lookups are performed and when it is set to False, lookups are not performed.
      
        - name: Set NTP on IOS Devices
          ios_ntp:
            server: "{{ items }}"
            logging: false
            state: present
            loop:
              - "{{ ListNTPServers | default([time-a-g.nist.gov,0.north-america.pool.ntp.org,time.google.com])}}"
          
      when: ansible_network_os == "ios"
    
    - name: Set NXOS Devices
      block: 
        - name: Set Hostname and Domain on NX-OS Devices
          nxos_system:
            state: present # not required. choices: present;absent. State of the configuration values in the device's current active configuration.  When set to I(present), the values should be configured in the device active configuration and when set to I(absent) the values should not be in the device active configuration
            name_servers: # not required. List of DNS name servers by IP address to use to perform name resolution lookups.  This argument accepts either a list of DNS servers See examples.
              - { server: "{{ NameServer1 }}", vrf: management }
              - { server: "{{ NameServer2 }}", vrf: management }
            hostname: "{{ HostName }}" # not required. Configure the device hostname parameter. This option takes an ASCII string value.            
            domain_name: "{{ DomainName }}" # not required. Configure the IP domain name on the remote device to the provided value. Value should be in the dotted name form and will be appended to the C(hostname) to create a fully-qualified domain name.
            domain_lookup: True # not required. Administrative control for enabling or disabling DNS lookups.  When this argument is set to True, lookups are performed and when it is set to False, lookups are not performed.
            system_mtu: default # not required. Specifies the mtu, must be an integer or keyword 'default'.

      when: ansible_network_os == "nxos"

