---
- name: "SET BANNER ON CISCO DEVICES"
  hosts: all
  gather_facts: no

  tasks:
    - name: Set IOS Devices
      block:                
      - name: CONFIGURE BANNER ON CISCO IOS DEVICES
        ios_banner:
          banner: login
          text: "{{ BannerText | default( lookup('file', './docs/banner.cfg') ) }}"
          state: present

      when: ansible_network_os == "ios"

    - name: Set NXOS Devices
      block:                
      - name: CONFIGURE BANNER ON CISCO NXOS DEVICES
        nxos_banner:
          banner: motd
          text: "{{ BannerText | default( lookup('file', './docs/banner.cfg') ) }}"
          state: present

      when: ansible_network_os == "nxos"