---
- name: "SET BANNER ON CISCO DEVICES"
  hosts: all
  gather_facts: no

  vars:
    BannerText: "{{ lookup('file', './docs/banner.cfg') }}"
  when: (BannerText is undefined) or (not BannerText)

  tasks:
    - name: Set IOS Devices
      block:                
      - name: CONFIGURE BANNER ON CISCO IOS DEVICES
        ios_banner:
          banner: login
          text: "{{ BannerText }}"
          state: present

      when: ansible_network_os == "ios"

    - name: Set NXOS Devices
      block:                
      - name: CONFIGURE BANNER ON CISCO NXOS DEVICES
        nxos_banner:
          banner: motd
          text: "{{ BannerText }}"
          state: present

      when: ansible_network_os == "nxos"