---
- name: "Get Cisco Device Info"
  hosts: all
  connection: network_cli
  gather_facts: no
  tasks:
    - name: Set vars for nxos
      set_fact:
        ansible_network_os: nxos
    - name: Gather Facts
      nxos_facts: